```plantuml
@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false
skinparam actorStyle stickman

actor "普通用户" as User

rectangle "标签模块" {
  usecase "查询标签列表" as UC1
  usecase "记录绑定标签" as UC2
}

User --> UC1
User --> UC2
@enduml
```